### ISSUE TITLE
doesn't run on RPI

### ISSUE THREAD

**Issue by wadoadi** [StancuFlorin/Google-Home-Samsung-Smart-TV-Integration#1]
I'm trying to run the script (Master branch) on my PI running jessie

Using python samsung-smart-tv-remote.py I get an error due the name in the PY for configparser being that used for python 3 renaming configparser on line 3 and 5 to ConfigParser and adding the () for the prints moves this on to other errors.

python3 samsung-smart-tv-remote.py gives multiple syntax errors e.g. print function needing (), __getitem__ not supported ...

Is this script for a PI!?

**Comment by StancuFlorin** [comment]
Can you try with Python 2?

**Comment by wadoadi** [comment]
With Python 2.7.9 and no changes to the script i get:
Traceback (most recent call last):
  File "samsung-smart-tv-remote.py", line 3, in <module>
    import configparser, pika, json, time, samsungctl
ImportError: No module named configparser

**Comment by wadoadi** [comment]
Then changing the configparser to ConfigParser as it appears to be using Python 3 naming "The ConfigParser module has been renamed to configparser in Python 3" but still running under Python 2.x i next get:

Traceback (most recent call last):
  File "samsung-smart-tv-remote.py", line 8, in <module>
    params = pika.URLParameters(config['CloudAMQP']['url'])
AttributeError: ConfigParser instance has no attribute '__getitem__'

**Comment by StancuFlorin** [comment]
I guess something changed in the configparser library. I will try with a fresh setup and I would let you know.

**Comment by wadoadi** [comment]
cool THANK YOU

**Comment by wadoadi** [comment]
Almost Working!
So here is what I have done so far and the error now seems to be in the JSon Payload! Current error    
     TypeError: the JSON object must be str, not 'bytes'

Actions thus far:

Install pika and samsungctl for Python 3 with pip3 
     Install pip3 install pika
     Install pip3 install samsungctl

Edit samsung-smart-tv-remote.py adding () to each print line

Run the python script using python3
     python3 samsung-smart-tv-remote.py



Error on Pi when message is read:

pi@xxxxxx:~/SamsungTV $ python3 samsung-smart-tv-remote.py
Traceback (most recent call last):
  File "samsung-smart-tv-remote.py", line 52, in <module>
    channel.start_consuming() # start consuming (blocks)
  File "/usr/local/lib/python3.4/dist-packages/pika/adapters/blocking_connection.py", line 1780, in start_consuming
    self.connection.process_data_events(time_limit=None)
  File "/usr/local/lib/python3.4/dist-packages/pika/adapters/blocking_connection.py", line 716, in process_data_events
    self._dispatch_channel_events()
  File "/usr/local/lib/python3.4/dist-packages/pika/adapters/blocking_connection.py", line 518, in _dispatch_channel_events
    impl_channel._get_cookie()._dispatch_events()
  File "/usr/local/lib/python3.4/dist-packages/pika/adapters/blocking_connection.py", line 1403, in _dispatch_events
    evt.body)
  File "samsung-smart-tv-remote.py", line 39, in callback
    message = json.loads(body)
  File "/usr/lib/python3.4/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

**Comment by StancuFlorin** [comment]
7 years latter, I created a PR to update the script to Python3 - https://github.com/StancuFlorin/google-assistant-samsung-smart-tv-integration/pull/3
